TC 19
TimeCroc/timecroc pull request #20
Opened 2023-05-04 00:43 UTC by KatAthay

Updated the pinpad display.

2023-05-04 18:26 UTC, markyencheske reviewed
Just leaving a comment here to note that we talked about adding arrow icons instead of using '<' and '>', as well as reformatting the border around the pinpad, and possibly changing the color of the pinpad buttons.

2023-05-08 18:46 UTC, markyencheske commented
<img width="713" alt="Screen Shot 2023-05-08 at 12 45 20 PM" src="https://user-images.githubusercontent.com/71556587/236906351-1a932743-22d3-4707-a2fc-06820b8ef678.png">


Everything looks awesome @KatAthay! Could you look into adjusting the pin display, seems like it just needs a little css adjusting?

2023-05-08 20:45 UTC, KatAthay commented
I fixed that this morning

2023-05-09 14:24 UTC, markyencheske requested changes

2023-05-09 14:24 UTC, markyencheske commented on client/components/App.js
> -            />}
@KatAthay Is there a reason you removed all of these routes? Now I'm getting errors when adding tips to an employees timesheet because these have been removed. 

I'm guessing it's because you were originally working on TC-19, then the main branch changed and you continued working on TC19 without merging in all the changes from main. I think because all these routes DO exist on the main branch, you may not have resolved merge conflicts properly when you merged the most recent version of main into TC19. 

Git is hard and confusing, don't get down on yourself because once you get in the flow it becomes like second nature. I can't approve this PR because of the breaking changes it would bring into the main branch, but all your styling changes look awesome! I'd recommend making a new branch called TC-19b, publish it, fire it up and merge main into the new branch to make sure you're fully up to date. Then re-implement (a pain, I know) all the styling changes that you made for this card and submit a new PR.

2023-05-09 16:19 UTC, closed without merging