TC-02
TimeCroc/timecroc pull request #4
Opened 2023-03-22 23:18 UTC by ClareCerullo

Created admin model, controller, and routes on the backend. Added functionality for:
-Get all admin users
-Get one admin user
-Add an admin user
-Update an admin user
-Delete an admin user

2023-03-22 23:19 UTC, KatAthay approved these changes
Looks good.

2023-03-22 23:21 UTC, markcharlessmith reviewed
Looks good!  Great work, team!

2023-03-23 03:12 UTC, markyencheske requested changes
Nice work overall y'all! The code is clear and easy to follow. See other comments for a couple follow up questions.

2023-03-23 03:12 UTC, markyencheske commented on server/models/adminModel.js
Asking because I genuinely don't know, is this file necessary or can we just rename the existing employeeModel and use it for both controllers? This seems to be the same logic from that file so I'm just assuming there's no difference between having two instances of the same thing or just using the same model for both? Thoughts @ClareCerullo @markcharlessmith @KatAthay ??

2023-03-23 03:12 UTC, markyencheske commented on server/server.js
looks good to me

2023-03-23 03:12 UTC, markyencheske commented on server/Routes/adminRoutes.js
this looks good to me

2023-03-23 03:12 UTC, markyencheske commented on server/Controllers/adminController.js
This looks good, but I'd expect to see some middleware for logging an admin in and out as well (along with a new column in the admin database to keep track of their logged in status. Could be my fault for not writing the card clearly enough. column could be called isLoggedIn or something and store a boolean value that is swapped based on their logged in status)

Also, bcrypt is in package.json but not used (unless I'm missing it?), is there a plan to implement that with authentication?

@ClareCerullo @markcharlessmith @KatAthay

2023-03-23 16:08 UTC, KatAthay commented on server/models/adminModel.js
The reason we created a separate file is so that if we needed to debug we could pinpoint which file was creating the issue. It is also our understanding that this naming convention follows best practices.

2023-03-23 16:10 UTC, markyencheske commented on server/models/adminModel.js
No that makes sense, was asking more out of curiosity.

2023-03-23 16:21 UTC, ClareCerullo commented on server/Controllers/adminController.js
We will add the login functionality in the middleware and update the admin database table. We will also implement authentication with bcrypt.

2023-03-23 16:36 UTC, markyencheske commented on server/Controllers/adminController.js
sounds good!

2023-03-29 21:30 UTC, markyencheske approved these changes
Looks great!

2023-03-29 21:30 UTC, markcharlessmith commented
Alright, the sessionController is all set!  And we accounted for admin logging out as well.

2023-03-29 21:31 UTC, merged